Dj/sliders
WalltoWall/workshop-v2 pull request #12
Opened 2023-11-06 14:43 UTC by davidjcreative

Happy to hear any feedback.

Please note that this does not include submitting an answer. Hadn't wrapped my head around that yet.

2023-11-06 20:33 UTC, asyarb commented
Hey @davidjcreative!

Just letting you know I'll look at this today. Stay tuned!

2023-11-07 03:36 UTC, asyarb requested changes
Overall looks good! We can talk on the side about the answer stuff. Otherwise, let me know if any of my comments need additional info or if you'd want to talk through them directly!

2023-11-07 03:36 UTC, asyarb commented on app/(site)/kickoff/[code]/exercises/[slug]/SlidersExercise.tsx
> +"use client"
In general, I've gone through and removed some unused imports and values to help reduce some of the noise for the review. Most of these smaller adjustments have been noted via a comment, but please feel free to let me know if any of it isn't clear!

2023-11-07 03:36 UTC, asyarb commented on app/(site)/kickoff/[code]/exercises/[slug]/SlidersExercise.tsx
> +}
While this works, this is pretty "non-reacty". We're modifying the DOM directly which is what we want React to be doing for us.

We can simplify this by moving this logic into our JSX:

```tsx
const Example = () => {
  const [value, setValue] = useState(0)

  return (
    <>
      <Image className={cx(value < 3.5 ? "opacity-100" : "opacity-0")} />
      <Image className={cx(value >= 3.5 ? "opacity-100" : "opacity-0")} />

      <input
        type="range"
        min={1}
        max={6}
        value={value}
        onChange={(e) => setValue(e.target.valueAsNumber)}
      />
    </>
  )
}
```

I've omitted a lot of the styling for brevity, but handling things this way also avoids some subtle bugs that were present in the previous version with duplicate IDs too.

2023-11-07 03:36 UTC, asyarb commented on app/(site)/kickoff/[code]/exercises/[slug]/SlidersExercise.tsx
> +									className="object-over object center opacity-1 h-full w-full transition ease-in-out"
There's a couple of typos and incorrect Tailwind classes here. `object-over` should be `object-cover`, `object center` should be `object-center`, `opacity-1` should be `opacity-100`, etc.

I'd recommend installing https://marketplace.visualstudio.com/items?itemName=bradlc.vscode-tailwindcss or the LSP server. I've personally found it really helpful during the initial learning phases since it provides visual hints and clues when a class is mis-spelled

2023-11-21 20:56 UTC, davidjcreative commented
@asyarb Let me know if there is anything else you want me to update on this!

2024-01-04 19:49 UTC, merged